(()=>{'use strict';const effects=new Set();let paused=false;const footer=document.querySelector('footer');let button=document.querySelector('#pause');if(!button){button=document.createElement('button');button.id='pause';footer.append(button)}
const active=()=>!paused&&!document.hidden;let schedule=()=>{};
function sync(){document.body.classList.toggle('studio-paused',paused||document.hidden);button.textContent=paused?'Resume motion':'Pause motion';button.setAttribute('aria-pressed',String(paused));effects.forEach(a=>active()?a.play():a.pause());document.dispatchEvent(new CustomEvent('hts-site-pause',{detail:{paused}}));document.dispatchEvent(new Event('hydetech-motion-change'));schedule()}
button.onclick=()=>{paused=!paused;sync()};document.addEventListener('visibilitychange',sync);
function animate(el,frames,opts={}){if(!el||paused)return;const a=el.animate(frames,{duration:750,easing:'cubic-bezier(.2,.7,.2,1)',...opts});effects.add(a);a.onfinish=()=>effects.delete(a);if(!active())a.pause();return a}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;observer.unobserve(e.target);animate(e.target,[{opacity:0,transform:'translateY(22px)'},{opacity:1,transform:'translateY(0)'}])}),{threshold:.12});
// Never target category pictures or a parent that would move them.
document.querySelectorAll('.hero-copy h1,.hero-copy p,.hero-copy .button,.page-hero h1,.page-hero .intro,.page-hero .actions,.services h2,.services p,.studio-demo-copy,.workflow,.owner figure,.owner>div,.owner-copy,.extra-services h2,.extra-grid article,.contact h2,.contact>div,.form-intro h1,.form-surface,.price-card,.faq-section h2,.policy h1').forEach(el=>observer.observe(el));
const hero=document.querySelector('.hero-art');if(hero){animate(hero,[{opacity:0},{opacity:1}],{duration:1100});animate(hero,[{transform:'scale(1) translateY(0)'},{transform:'scale(1.018) translateY(-5px)'},{transform:'scale(1) translateY(0)'}],{duration:18000,iterations:Infinity,easing:'ease-in-out'})}
const glitch=document.querySelector('.glitch-ai');if(glitch)animate(glitch,[{offset:0,textShadow:'2px 0 #faae55',transform:'translateX(0)'},{offset:.88,textShadow:'2px 0 #faae55',transform:'translateX(0)'},{offset:.91,textShadow:'-3px 0 #ed4d25,3px 0 #faae55',transform:'translateX(-1px)'},{offset:.94,textShadow:'3px 0 #ed4d25,-2px 0 #faae55',transform:'translateX(1px)'},{offset:1,textShadow:'2px 0 #faae55',transform:'translateX(0)'}],{duration:4200,iterations:Infinity});
document.querySelectorAll('.button,.plain-link,.row-link,nav a').forEach(el=>{el.addEventListener('pointerenter',()=>animate(el,[{transform:'translateY(0)'},{transform:'translateY(-2px)'},{transform:'translateY(0)'}],{duration:350}));});
const workflow=document.querySelector('.workflow');if(workflow){let visible=false,hover=false,focused=false,auto=true,timer;const playback=document.createElement('button');playback.type='button';playback.className='flow-playback';playback.textContent='Pause demo';playback.setAttribute('aria-pressed','true');workflow.querySelector('.workflow-heading').append(playback);schedule=()=>{clearInterval(timer);if(active()&&auto&&visible&&!hover&&!focused)timer=setInterval(()=>workflow.dispatchEvent(new Event('workflow-advance')),5000)};playback.onclick=()=>{auto=!auto;playback.textContent=auto?'Pause demo':'Play demo';playback.setAttribute('aria-pressed',String(auto));schedule()};workflow.addEventListener('pointerenter',()=>{hover=true;schedule()});workflow.addEventListener('pointerleave',()=>{hover=false;schedule()});workflow.addEventListener('focusin',()=>{focused=true;schedule()});workflow.addEventListener('focusout',e=>{focused=workflow.contains(e.relatedTarget);schedule()});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;schedule()},{threshold:.4}).observe(workflow)}
document.querySelectorAll('.demo-next,[data-scenario]').forEach(el=>el.addEventListener('click',()=>animate(document.querySelector('.conversation'),[{opacity:.3,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:300})));
sync();})();
